name: CI Pipeline for the main branch

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:

  docker-image-main:
    name: Docker Image (for the main branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: $ {{ secrets.DOCKER_HUB_USERNAME }}/spring-petclinic-mr:latest
